projeto/accounts/urls.py
# accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from django.contrib.auth import get_user_model
User = get_user_model()
from projeto.accounts import views
app_name='accounts'

urlpatterns = [
 #não existe mais mas não tenho coragem de deletar ainda   path('signup/', views.SignUp.as_view(), name='signup'), 
    path('', auth_views.LoginView.as_view(), name='login'),
    path('cadastro/', views.CadastroView.as_view(), name='cadastro'), 
    path('cadastro/aluno/', views.CadastroAlunoView.as_view(), name='cadastro_aluno'),
    path('cadastro/professor/', views.CadastroProfessorView.as_view(), name='cadastro_professor'),

]

projeto/boards/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from projeto.boards import views
app_name='boards'


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('boards/<int:pk>/', views.board_topics, name='board_topics'),
    path('boards/new/', views.new_board, name='new_board'),
    path('boards/<int:pk>/new/', views.new_topic, name='new_topic'),
]

projeto/edp/urls.py
# accounts/urls.py
from django.urls import path
from django_filters.views import FilterView
from django.contrib.auth import views as auth_views
from projeto.edp.filters import EdpFilter
from . import views
app_name='edp'

urlpatterns = [
    path('', views.edps, name='edps'),
    path('minhas', views.minhas_edps, name='minhas_edps'),
    path('minhas/aluno', views.minhas_edps_aluno, name='minhas_edps_aluno'),
    path('edp/respondidas', views.listarRespostasEDA, name='respondidas'),

    path('aluno/<int:id>/respostas', views.respostasEdp, name='resposta_edp'),

    path('edp/<slug:slug>/alunos', views.listaAlunosResponderamEdp, name='responderam'),
    path('edp/detalhes/<slug:slug>', views.detalhe_edp, name= 'detalhe_edp'),
    path('edp/nova', views.nova_edp, name= "nova_edp"),
    path('edp/adicionar/recursos/<slug:slug>', views.adicionar_recursos, name= "adicionar_recursos"),
    path('edp/editar/<slug:slug>/', views.editar_edp, name= "editar_edp"),
    path('edp/recursos/editar/<slug:slug>/', views.editar_recursos, name='editar_recursos'),
    path('edp/deletar/<slug:slug>/', views.deletar_edp, name= "deletar_edp"),
    path('edp/responder/<slug:slug>/', views.responder_edp, name="responder_edp"),
    path('edp/pesquisa/', views.pesquisaEdp, name='pesquisa'),
    path('edp/tradutor', views.traducao, name='tradutor'),

    # path('api/tradutor', views.traducao, name='traducao'),

]

projeto/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.conf import settings
from projeto.edp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projeto.accounts.urls', namespace='accounts')),
    path('edps/', include('projeto.edp.urls', namespace='edp')),
    path('forum/', include('projeto.boards.urls', namespace='boards')),
    path('accounts/', include('django.contrib.auth.urls')),



]
urlpatterns += staticfiles_urlpatterns()


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

urlpatterns += [

    path('tinymce/', include('tinymce.urls')),
]

projeto/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    eh_aluno = models.BooleanField(default=False)
    eh_professor = models.BooleanField(default=False)

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    nivel = models.IntegerField('Nível de proficiência', default=0,blank=True)
    name = models.TextField()
    def __str__(self):
        return self.user.username
    

projeto/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from projeto.accounts.models import Student
from django.db import transaction

from django.contrib.auth import get_user_model
User = get_user_model()

class CadastroAlunoForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
# TODO: pedir nome, sobrenome e email!! para evitar confusão no usuario
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.eh_aluno = True
        user.save()
        student = Student.objects.create(user=user, nivel=0)

        return user
        

class CadastroProfessorForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.eh_professor = True
        if commit:
            user.save()
        return user

projeto/accounts/views.py
# accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import (get_object_or_404, redirect, render,
                              render_to_response)
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, TemplateView

from projeto.accounts.forms import CadastroAlunoForm, CadastroProfessorForm
from projeto.accounts.models import Student, User
from django.contrib.auth import get_user_model
User = get_user_model()

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

class CadastroAlunoView(CreateView):
    model = User
    form_class = CadastroAlunoForm
    template_name = 'registration/cadastroForm.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'aluno'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('edp:edps')

class CadastroProfessorView(CreateView):
    model = User
    form_class = CadastroProfessorForm
    template_name = 'registration/cadastroForm.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'professor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('edp:edps')


class CadastroView(TemplateView):
    template_name = 'registration/cadastro.html'

projeto/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  
    
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="raissa">
    <meta name="author" content="adalin">

    <title>{% block title %} ADAPLE - {{title}} {% endblock %}</title>
    <title>Ambiente Digital de Aprendizagem de Portugues como Lingua Estrangeira</title>


    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href=" {% static 'vendor/metisMenu/metisMenu.min.css' %}   " rel="stylesheet">

    <!-- Custom CSS -->
    <link href=" {% static 'dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href=" {% static 'vendor/morrisjs/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href=" {% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">

    <!-- jQuery -->
    <script src=" {% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    {% block stylesheet %}{% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button> 
                <!-- TODO: icon brand?? -->
                <a class="navbar-brand" href="{% url 'edp:edps' %}">Ambiente Digital para Aprendizagem de Línguas</a>
            </div>
            <!-- /.navbar-header -->


            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    Bem vindo(a) <b>{{user.username}}</b> !
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        {% if user.is_authenticated %}
                            <li><a href="#"><i class="fa fa-user fa-fw"></i> {{user.username}}</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
                            </li>
<!-- TODO: tirar esse if e else, para tá nessa pg tem q tá logado sim!!  -->
                            {%else%}
                            <li><a href="{% url 'login' %}"><i class="fa fa-sign-in fa-fw"></i> Entrar</a>
                            </li>
                        {% endif %}
    

                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            {% if user.is_authenticated and user.eh_professor %}
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                       
                        <li>
                            <a href="{% url 'edp:edps' %}"><i class="fa fa-dashboard fa-fw"></i> Página Inicial</a>
                        </li>
                        <li>
                            <a href="{% url 'edp:edps' %}"><i class="fa fa-bar-chart-o fa-fw"></i><abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr>
                                
                                
                                <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'edp:edps' %}">Todas</a>
                                </li>
                                <li>
                                    <a href="{% url 'edp:minhas_edps' %}">Minhas</a>
                                </li>
                                <li>
                                    <a href="{% url 'edp:pesquisa' %}">Pesquisar</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="{% url 'edp:respondidas' %}"><i class="fa fa-table fa-fw"></i> <abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr> Respondida</a>
                        </li>
                        <li>
                            <a href="{% url 'boards:home' %}"><i class="fa fa-edit fa-fw"></i> Fórum</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
     
            {% elif user.is_authenticated and user.eh_aluno %}
            
            <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                       
                            <li>
                                <a href="{% url 'edp:edps' %}"><i class="fa fa-dashboard fa-fw"></i> Página Inicial</a>
                            </li>
                            <li>
                                <a href="{% url 'edp:edps' %}"><i class="fa fa-bar-chart-o fa-fw"></i><abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr><span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{% url 'edp:edps' %}">Todas</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'edp:minhas_edps_aluno' %}">Minhas</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'edp:pesquisa' %}">Pesquisar</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-table fa-fw"></i> <abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr> Respondida</a>
                            </li>
                            <li>
                                <a href="{% url 'boards:home' %}"><i class="fa fa-edit fa-fw"></i> Fórum</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
            
            
            {% endif %}

            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
        
        {% block dashboard %}
            
        {% endblock dashboard %}
            
        </div>


    </div>
    <!-- /#wrapper -->


    <!-- Bootstrap Core JavaScript -->
    <script src=" {% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{% static 'vendor/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'vendor/morrisjs/morris.min.js' %}"></script>
    <!-- <script src="s../data/morris-data.js"></script> -->

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'dist/js/sb-admin-2.js' %}"></script>

    
    {% block JavaScript %}
        
    {% endblock JavaScript %}
        
</body>

</html>