projeto/boards/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from projeto.boards import views
app_name='boards'


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('boards/<int:pk>/', views.board_topics, name='board_topics'),
    path('boards/new/', views.new_board, name='new_board'),
    path('boards/<int:pk>/new/', views.new_topic, name='new_topic'),
]

projeto/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.conf import settings
from projeto.edp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projeto.accounts.urls', namespace='accounts')),
    path('edps/', include('projeto.edp.urls', namespace='edp')),
    path('forum/', include('projeto.boards.urls', namespace='boards')),
    path('accounts/', include('django.contrib.auth.urls')),



]
urlpatterns += staticfiles_urlpatterns()


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

urlpatterns += [

    path('tinymce/', include('tinymce.urls')),
]

projeto/boards/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models
User = get_user_model()


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name='topics', on_delete=models.CASCADE)


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null=True, related_name='+', on_delete=models.CASCADE)

projeto/boards/forms.py
from django import forms

from .models import Topic, Board

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'O que você pensa?',}
        ),
        label="Mensagem",
        max_length=4000,
        help_text='Tamanho máximo 4000 caracteres.'
    )
    subject=forms.CharField(max_length=150, label="Assunto")

    class Meta:
        model = Topic
        fields = ['subject', 'message']

class NewBoardForm(forms.ModelForm):
    name = forms.CharField(label="Nome",
        max_length=30
    )
    description=forms.CharField(max_length=100, label="Descrição")

    class Meta:
        model = Board
        fields = ['name', 'description']

projeto/boards/views.py
# TODO: pesquisar sobre isso get_list_or_404
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
User = get_user_model()

from .forms import NewTopicForm, NewBoardForm
from .models import Board, Topic, Post


def home(request):
    boards = Board.objects.all()
    return render(request, 'boards/home.html', {'boards': boards})


def board_topics(request, pk):
    board = get_object_or_404(Board, pk=pk)
    return render(request, 'boards/topics.html', {'board': board})


def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    user = request.user
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = user
            topic.save()
            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=user
            )
            # TODO: redirect to the created topic page
            return redirect('boards:board_topics', pk=board.pk)
    else:
        form = NewTopicForm()
    return render(request, 'boards/new_topic.html', {'board': board, 'form': form})


def new_board(request):
    template = 'boards/new_board.html'

    if request.method == "POST":
        form = NewBoardForm(request.POST)
        if form.is_valid():

            edp = form.save(request)

            edp.save()

            return redirect('boards:home')
    else:
        form = NewBoardForm()
        return render(request, template, {'form': form})

projeto/boards/templates/boards/home.html
{% extends 'base.html' %}
{% block dashboard %}

<div>

<div style="padding-top: 20px;padding-bottom: 20px;">{% if user.is_authenticated and user.eh_professor %}
    <a href="{% url 'boards:new_board' %}" class="btn btn-success btn-lg ">Novo Quadro de Tópicos</a>
    {% endif %}</div>
</div>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Fórum</th>
        <th>Postagens</th>
        <th>Tópicos</th>
        <th>Última postagem</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            <a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

projeto/boards/templates/boards/new_board.html
{% extends 'base.html' %}

{% block title %}Comece um novo tópico de discussão{% endblock %}




{% block dashboard %}
<div class="row">
<h1 class="page-header">Novo Quadro</h1>

</div>
<div class="row">

<form method="post" novalidate>
    {% csrf_token %}
    {% include 'boards/includes/form.html' %}
    <button type="submit" class="btn btn-success">Criar</button>
  </form>

</div>

{% endblock %}

projeto/boards/templates/boards/new_topic.html
{% extends 'base.html' %}

{% block title %}Comece um novo tópico de discussão{% endblock %}




{% block dashboard %}
<div class="row">
<h1 class="page-header">Novo Tópico</h1>

</div>
<div class="row">

<form method="post" novalidate>
    {% csrf_token %}
    {% include 'boards/includes/form.html' %}
    <button type="submit" class="btn btn-success">Postar</button>
  </form>

</div>

{% endblock %}

projeto/boards/templates/boards/topic_posts.html
{% extends 'base.html' %}

{% load gravatar %}

{% block title %}{{ topic.subject }}{% endblock %}


{% block dashboard %}

  <div class="mb-4">
    <a href="{% url 'reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
  </div>

  {% for post in posts %}
    <div id="{{ post.pk }}" class="card {% if forloop.last %}mb-4{% else %}mb-2{% endif %} {% if forloop.first %}border-dark{% endif %}">
      {% if forloop.first %}
        <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
      {% endif %}
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{{ post.created_by|gravatar }}" alt="{{ post.created_by.username }}" class="w-100 rounded">
            <small>Posts: {{ post.created_by.posts.count }}</small>
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_at }}</small>
              </div>
            </div>
            <div class="post-body">
              {{ post.get_message_as_markdown }}
            </div>
            {% if post.created_by == user %}
              <div class="mt-3">
                <a href="{% url 'edit_post' post.topic.board.pk post.topic.pk post.pk %}"
                   class="btn btn-primary btn-sm"
                   role="button">Edit</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

{% endblock %}

projeto/boards/templates/boards/topics.html
{% extends 'base.html' %}

{% block title %}
  {{ board.name }} - {{ block.super }}
{% endblock %}

{% block dashboard %}
 
  <div style="padding-top: 20px;padding-bottom: 20px;">
      <a href="{% url 'boards:new_topic' board.pk %}" class="btn btn-primary">Novo Tópico</a>
   </div>
  
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Tópico</th>
        <th>Autor</th>
        <th>Respostas</th>
        <th>Visualizações</th>
        <th>Ultima atualização</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in board.topics.all %}
        <tr>
          <td>{{ topic.subject }}</td>
          <td>{{ topic.starter.username }}</td>
          <td>0</td>
          <td>0</td>
          <td>{{ topic.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}