projeto/edp/urls.py
# accounts/urls.py
from django.urls import path
from django_filters.views import FilterView
from django.contrib.auth import views as auth_views
from projeto.edp.filters import EdpFilter
from . import views
app_name='edp'

urlpatterns = [
    path('', views.edps, name='edps'),
    path('minhas', views.minhas_edps, name='minhas_edps'),
    path('minhas/aluno', views.minhas_edps_aluno, name='minhas_edps_aluno'),
    path('edp/respondidas', views.listarRespostasEDA, name='respondidas'),

    path('aluno/<int:id>/respostas', views.respostasEdp, name='resposta_edp'),

    path('edp/<slug:slug>/alunos', views.listaAlunosResponderamEdp, name='responderam'),
    path('edp/detalhes/<slug:slug>', views.detalhe_edp, name= 'detalhe_edp'),
    path('edp/nova', views.nova_edp, name= "nova_edp"),
    path('edp/adicionar/recursos/<slug:slug>', views.adicionar_recursos, name= "adicionar_recursos"),
    path('edp/editar/<slug:slug>/', views.editar_edp, name= "editar_edp"),
    path('edp/recursos/editar/<slug:slug>/', views.editar_recursos, name='editar_recursos'),
    path('edp/deletar/<slug:slug>/', views.deletar_edp, name= "deletar_edp"),
    path('edp/responder/<slug:slug>/', views.responder_edp, name="responder_edp"),
    path('edp/pesquisa/', views.pesquisaEdp, name='pesquisa'),
    path('edp/tradutor', views.traducao, name='tradutor'),

    # path('api/tradutor', views.traducao, name='traducao'),

]

projeto/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.conf import settings
from projeto.edp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projeto.accounts.urls', namespace='accounts')),
    path('edps/', include('projeto.edp.urls', namespace='edp')),
    path('forum/', include('projeto.boards.urls', namespace='boards')),
    path('accounts/', include('django.contrib.auth.urls')),



]
urlpatterns += staticfiles_urlpatterns()


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

urlpatterns += [

    path('tinymce/', include('tinymce.urls')),
]

projeto/edp/models.py
import os

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.utils import timezone
from embed_video.fields import EmbedVideoField
from tinymce.models import HTMLField
from projeto.accounts.models import Student
STATIC_CUR_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'static')

upload_storage = FileSystemStorage(location=STATIC_CUR_DIR)



User = get_user_model()

class Habilidade (models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome


class Edp(models.Model):
    NIVEL_CHOICES = (
		(0, 'Básico (Sem certificação)'),
		(1, 'Intermediário'),
		(2, 'Intermediário Superior'),
        (3, 'Avançado'),
        (4, 'Avançado Superior')
	)

    titulo = models.CharField('Título', max_length=100)
    slug = models.SlugField('Atalho')
    objetivo_pedagogico = models.TextField('Objetivo Pegagogico')
    habilidades = models.ManyToManyField(Habilidade, related_name='habilidade_edp')    
    atividades = models.TextField('Atividades')
    metodologia = models.TextField('Metodologia')
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='edps', on_delete=models.CASCADE)
    nivel = models.IntegerField('Nível de proficiência', choices=NIVEL_CHOICES, default=0,blank=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def iniciar(self):
        self.save()

    def __str__(self):
        return self.titulo
    
    @models.permalink
    def get_absolute_url(self):
        return ('edp:detalhe_edp', (), {'slug': self.slug})

    
    class Meta:
        verbose_name = 'Estrutura Digital de Aprendizagem'
        verbose_name_plural = 'Estruturas Digital de Aprendizagem'
        ordering = ['-created_at']

class RecursosEdp(models.Model):
   
    # edp = models.ForeignKey(Edp, verbose_name='Edp', related_name='recursos', on_delete=models.CASCADE)
    edp = models.OneToOneField(Edp, verbose_name='Edp',  related_name='recursos', on_delete=models.CASCADE)
    video_embedded = EmbedVideoField(blank=True, null=True)
    texto =  models.TextField('Texto', blank=True)
    recebe_texto = models.BooleanField('Responder texto ?', default=False)
    recebe_video_embedded = models.BooleanField('Responder com videos do youtube?', default=False )
    recebe_video = models.BooleanField('Responder com video?', default=False)
    recebe_imagem = models.BooleanField('Responder com imagem ?', default=False)
    video = models.FileField(upload_to='video/', storage=upload_storage, default="media/none.mp4")


    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.edp.titulo
    
    def iniciar(self):
        self.save()
 
    @models.permalink
    def get_absolute_url(self):
        return ('edp:detalhe_edp', (), {'slug': self.slug})

    
    class Meta:
        verbose_name = 'Recurso Estrutura Digital de Aprendizagem'
        verbose_name_plural = 'Recursos Estruturas  Digital de Aprendizagem'
        ordering = ['created_at']

        
class RespostaEdp(models.Model):
   
    edp = models.ForeignKey(Edp, verbose_name='Edp', related_name='respostas', on_delete=models.CASCADE)
    video_embedded = EmbedVideoField(blank=True, null=True)
    texto = models.TextField('Texto', blank=True)
    video = models.FileField(upload_to='video/', storage=upload_storage, default="media/none.mp4")
    aprendiz = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='aluno', related_name='respostaAluno', on_delete=models.CASCADE)
    # aprendiz = models.ForeignKey(Student, verbose_name='aprendiz ', related_name='respostaAprendiz', on_delete=models.CASCADE)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)


    def __str__(self):
        return self.edp.titulo + " - " + self.aprendiz.username
    
    def iniciar(self):
        self.save()
    @models.permalink
    def get_absolute_url(self):
        return ('edp:detalhe_edp_resposta', (), {'slug': self.slug})

    class Meta:
        verbose_name = 'Resposta Estrutura Digital de Aprendizagem'
        verbose_name_plural = 'Resposta Estrutura Digital de Aprendizagem'
        ordering = ['-created_at']

projeto/edp/views.py
import json

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.http import (Http404, HttpRequest, HttpResponse,
                         HttpResponseRedirect, JsonResponse,
                         StreamingHttpResponse)
from django.shortcuts import (get_list_or_404, get_object_or_404, redirect,
                              render, render_to_response)
from django.urls import reverse
from django.utils.text import slugify
from django.views.decorators.csrf import csrf_exempt
from rest_framework.response import Response

from .decorators import student_required, teacher_required
from .filters import EdpFilter
from .forms import Edp_form, form_recursos_edp, form_resposta_edp
from watson_developer_cloud import LanguageTranslatorV3
from .models import Edp, Habilidade, RecursosEdp, RespostaEdp

User = get_user_model()

@login_required
def edps(request):

    edps = Edp.objects.all()
    recursos = RecursosEdp.objects.all()
    title = 'Estruturas Digitais Pedagogicas'
    template = 'edp/listarEDA.html'
    user = request.user
    if request.user.eh_aluno == True:
        edps_nivel = edps.exclude(nivel=user.student.nivel)
    else:
        edps_nivel = edps #gambiarra
    
    # print(edps_nivel)

    # for x in user.respostaAluno.all():
    #     nivelx = x.edp.nivel
       
    #     print (nivelx == user.student.nivel )
    # user.respostaAluno.filter()

    return render(request, template, {'title': title, 'edps': edps,'edps_nivel':edps_nivel ,'recursos': recursos})

@teacher_required
def minhas_edps(request):
    edps = request.user.edps.all()
    recursos = RecursosEdp.objects.all()
    title = 'Estruturas Digitais Pedagogicas'
    template = 'edp/listarEDA.html'
    if request.user.eh_professor == True:
        return render(request, template, {'title': title, 'edps': edps, 'recursos': recursos})
    else:
        return redirect('edp:epds')

@student_required
def minhas_edps_aluno(request):
    respostas = request.user.respostaAluno.all()
    recursos = RecursosEdp.objects.all()
    edps = list()


    for e in respostas:
        edps.append(e.edp)

    title = 'Estruturas Digitais Pedagogicas'
    template = 'edp/listarEDA.html'
    if request.user.eh_aluno == True:
        return render(request, template, {'title': title, 'edps': edps, 'recursos': recursos})
    else:
        return redirect('edp:epds')

@teacher_required
def detalhe_edp(request, slug):

    edp = get_object_or_404(Edp, slug=slug)
    recursos = get_object_or_404(RecursosEdp, edp=edp)
    form = form_resposta_edp()
    template = 'edp/edp_detalhes.html'
    title = edp.titulo + '- Detalhes'
    return render(request, template, {'title': title, 'edp': edp, 'recursos': recursos, 'form': form})

@teacher_required
def nova_edp(request):
    template = 'edp/edp_nova.html'
    title = 'Criar nova'
    if request.method == "POST":
        form = Edp_form(request.POST)
        if form.is_valid():

            edp = form.save(request)

            edp.slug = slugify(edp.titulo)+"-"+str(edp.pk)
            edp.save()

        return redirect('edp:edps')
    else:
        form = Edp_form()
        return render(request, template, {'form': form})

@teacher_required
def editar_edp(request, slug):
    edp = get_object_or_404(Edp, slug=slug)

    template = 'edp/edp_nova.html'
    title = 'Editar EDA' + edp.titulo
    if request.method == 'POST':
        form = Edp_form(request.POST, instance=edp)
        if form.is_valid():
            form.save(request)
            return redirect('edp:edps')
    else:
        form = Edp_form(instance=edp)
    return render(request, template, {'form': form})

@teacher_required
def deletar_edp(request, slug):
    template = 'edp/edp_deletar.html'
    edp = get_object_or_404(Edp, slug=slug)
    if request.method == 'POST':
        edp.delete()
        return redirect('edp:edps')
    return render(request, template, {'edp': edp})

@teacher_required
def adicionar_recursos(request, slug):
    edp = get_object_or_404(Edp, slug=slug)
    template = 'edp/adicionar_recursos.html'
    title = 'Adicionar Recursos a EDA - ' + edp.titulo
    uploaded_file_url = 'media/none.mp4'


    if request.method == "POST":
        print("\nPOST\n")
        form = form_recursos_edp(request.POST, request.FILES)

        if 'video' in request.FILES:
            myfile = request.FILES['video']
            #form = UploadFileForm(request.POST, request.FILES)
            fs = FileSystemStorage()
            filename = fs.save('video/' + myfile.name, myfile)
            uploaded_file_url = fs.url(filename)

        if form.is_valid():

            recursos_edp = form.save(commit=False)
            recursos_edp.edp = edp
            recursos_edp.video=uploaded_file_url
            recursos_edp.save()
            return HttpResponse(json.dumps({'url': reverse("edp:edps"), 'alerta': 'Recursos adicionados a EDA com sucesso'}), content_type='application/json')
        else:
            print(form.errors.as_json)
            return redirect('edp:edps')
    else:
        form = form_recursos_edp()
        return render(request, template, {'form': form, 'title': title, 'edp': edp})

@teacher_required
def editar_recursos(request, slug):
    edp = get_object_or_404(Edp, slug=slug)
    recursos = get_object_or_404(RecursosEdp, edp=edp)
    template = 'edp/adicionar_recursos.html'
    title = 'Editar Recursos da EDA - ' + edp.titulo
    uploaded_file_url = recursos.video

    if request.method == "POST":
        print("\nPOST\n")
        form = form_recursos_edp(request.POST, request.FILES, instance=recursos)

        if 'video' in request.FILES:
            myfile = request.FILES['video']
            # form = UploadFileForm(request.POST, request.FILES)
            fs = FileSystemStorage()
            filename = fs.save('video/' + myfile.name, myfile)
            uploaded_file_url = fs.url(filename)

        if form.is_valid():
            form.video=uploaded_file_url
            form.save(request)
            return HttpResponse(json.dumps({'url': reverse("edp:edps"), 'alerta':'Editado com sucesso!'}), content_type='application/json')
        else:
            print(form.errors.as_json)
            return redirect('edp:edps')
    else:
        form = form_recursos_edp(instance=recursos)
        return render(request, template, {'form': form, 'title': title, 'edp': edp})

@teacher_required
def editar_edp(request, slug):
    edp = get_object_or_404(Edp, slug=slug)

    template = 'edp/edp_nova.html'
    title = 'Editar EDA' + edp.titulo
    if request.method == 'POST':
        form = Edp_form(request.POST, instance=edp)
        if form.is_valid():
            form.save(request)
            return redirect('edp:edps')
    else:
        form = Edp_form(instance=edp)
    return render(request, template, {'form': form})

@student_required
def responder_edp(request, slug):
    edp = get_object_or_404(Edp, slug=slug)
    recursos = get_object_or_404(RecursosEdp, edp=edp)
    template = 'edp/edp_responder.html'
    title = 'Responder a EDA - ' + edp.titulo
    uploaded_file_url = 'media/none.mp4'
    if request.method == "POST":
        print("\nPOST\n")
        form = form_resposta_edp(request.POST, request.FILES)

        if 'video' in request.FILES:
            myfile = request.FILES['video']
            #form = UploadFileForm(request.POST, request.FILES)
            fs = FileSystemStorage()
            filename = fs.save('video/' + myfile.name, myfile)
            uploaded_file_url = fs.url(filename)

        if form.is_valid():

            resposta = form.save(commit=False)
            resposta.video=uploaded_file_url
            resposta.edp = edp
            resposta.aprendiz = request.user
           
            resposta.save()
            return HttpResponse(json.dumps({'url': reverse("edp:edps"), 'alerta': 'Recursos adicionados a EDA com sucesso'}), content_type='application/json')
            
        else:
            print(form.errors.as_json)
            return redirect('edp:edps')
    else:
        form = form_resposta_edp()
        return render(request, template, {'form': form, 'title': title, 'edp': edp, 'recursos': recursos})

@login_required
def pesquisaEdp(request):
    template_name = 'edp/pesquisa.html'
    title = "Pesquisa"
    edps = Edp.objects.all()
    edps_pesquisa = EdpFilter(request.GET, queryset=edps)

    return render(request, template_name, {'edps_pesquisa': edps_pesquisa, 'title': title})

@teacher_required
def listarRespostasEDA(request):

    edpsTodas = Edp.objects.all()
    title = 'Estruturas Digitais Pedagogicas - Lista de EDA respondidas'
    template = 'edp/listarEDArespondida.html'
    edps = list()
   
   
    for edp in edpsTodas:
        
        if edp.respostas.all().count() != 0:
        
            edps.append(edp)
            
    print("\n--- Lista de respondidas \n ")
    return render(request, template, {'title': title, 'edps': edps})

def listaAlunosResponderamEdp(request, slug):
    edp = get_object_or_404(Edp, slug=slug)
    respostas = RespostaEdp.objects.filter(edp=edp).order_by('-aprendiz')
    lista_aprendiz=list()

    for r in range(len(respostas)):
        if r==0:
            lista_aprendiz.append(respostas[r])
        else:
            if respostas[r].aprendiz == respostas[r-1].aprendiz:
                pass
            else:
                lista_aprendiz.append(respostas[r])
    return render(request, 'edp/lista_alunos_EDARespondida.html', {'lista':lista_aprendiz})


def respostasEdp(request, id):
    resposta = get_object_or_404(RespostaEdp, id=id)
    edp = get_object_or_404(Edp, pk = resposta.edp.pk)
    aprendiz = get_object_or_404(User, pk = resposta.aprendiz.pk)
    respostas_edp = RespostaEdp.objects.filter(edp=edp, aprendiz=aprendiz)
    

projeto/edp/templates/edp/edp_criar.html
<!-- templates/home.html-->
{% extends 'dashboard.html' %} {% block title %} {{title}}{% endblock %} {% block dashboard_content %}


<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
      </form>


{% endblock %}

projeto/edp/templates/edp/edp_listarRespondidas.html
{% extends 'base.html' %} {% block title %} {{title}}{% endblock %}
{%load widget_tweaks %}



{% block dashboard %}

<table  class="table table-hover table-stripped table-responsive-sm table-sm">
    <thead>
      <tr>
        <th scope="col table-bordered">Título</th>
        <th scope="col">Habilidades</th>
        <th scope="col">Nível</th>
        <th scope="col">Data</th>
        <th scope="col">Professor(a)</th>
      </tr>
    </thead>
    {% for edp in edps%}
    <tbody>
      <tr>
        <th scope="row">


            <a  {% if edp.recursos %} href="{{edp.get_absolute_url}}" {%endif%} >{{edp}}</a></th>
        <td>{% for h in edp.habilidades.all %}
            <ul class="list-group">
                <li class="ml-4">{{h}}</li>
            </ul>
            {%endfor%}</td>
        <td>{{edp.get_nivel_display}}</td>
        <td>{{edp.created_at |date:"d/m/Y"}}</td>
        <td>{{edp.usuario}}</td>
  {% empty%}
   <td>Nenhuma <abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr> disponível.</td>
      </tr>

    </tbody>

    {%endfor%}

  </table>


{% endblock %}

projeto/edp/templates/edp/edps.html
<!-- templates/home.html-->
{% extends 'base.html' %} {% block title %} {{title}}{% endblock %} {% block breadcrumb %}

<li class="breadcrumb-item active">EDA</li>
{% endblock%} {% block content %}

<a href="{% url 'edp:nova_edp' %}" class="btn btn-warning btn-lg ">Nova EDP</a>
<div style="padding: 10px;"></div>
<div class="list-group">
    {% for edp in edps%}

    <a class="list-group-item list-group-item-action flex-column align-items-start ">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{edp}}</h5>
            <small>{{edp.created_at}}</small>
        </div>
        <p class="mb-1">
            <strong>Objetivo: </strong>{{edp.objetivo_pedagogico}}</p>
        <p class="mb-1">
            <strong>Atividades: </strong>{{edp.atividades}}</p>
        <p class="mb-1">
            <strong>Metodo: </strong>{{edp.metodologia}}</p>


        <small class="list-footer text-right">
            <a href="{% url 'edp:detalhe_edp' edp.slug %}" class="btn btn-primary ">Detalhes</a>
            <a href="{% url 'edp:adicionar_recursos' edp.slug %}" class="btn btn-info ">+ recursos</a>
            <a href="{% url 'edp:nova_resposta_edp' edp.slug  %}" class="btn btn-danger ">+ resposta</a>
        </small>
    </a>

    {% endfor %}
</div>












{% endblock %}

projeto/edp/templates/edp/lista_alunos_EDARespondida.html
{% extends 'base.html' %} {% block title %} {{title}}{% endblock %} 
                

{% block dashboard %}

<div style="padding: 10px;"></div>


<table class="table table-hover table-stripped table-responsive-sm table-sm">
    <thead>
      <tr>
        <th scope="col table-bordered">Título</th>
        <th scope="col">Respostas</th>
        <th scope="col">Ultima Resposta</th>       
      </tr>
    </thead>    {% for l in lista %}
    <tbody>
      <tr>
        <th scope="row">
            
        <a href="{% url 'edp:resposta_edp' l.id %}">{{l}}</a>
 </th>
  <td>{{l.all.count}}</td>
<th></th>     
</tr>

    </tbody>
    {%endfor%}
  </table>


{% endblock %}

projeto/edp/templates/edp/listarEDA.html
{% extends 'base.html' %} {% block title %} {{title}}{% endblock %}
{%load widget_tweaks %}



{% block dashboard %}

<div style="padding-top: 20px;padding-bottom: 20px;">{% if user.is_authenticated and user.eh_professor %}
<a href="{% url 'edp:nova_edp' %}" class="btn btn-success btn-lg ">Nova <abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr></a>
{% endif %}</div>

<script>
$(document).ready( function () {
    $('#myTable').DataTable(
    {
            "columnDefs": [
                { "orderable": true, "targets": 0 }
        ],
    paging: false
}    );

} );


</script>
{% if user.is_authenticated and user.eh_aluno %}
<div class="row">
        <div class="col-lg-12">
              
              <h3 class="page-header"> Sugestões</h3>
        </div>
        <!-- /.col-lg-12 -->
      </div>
      
  <div class="row">

{% for edp  in edps_nivel %}

<div class="col-lg-3 col-md-6">
    <div class="panel panel-green">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-3">
                    <i class="fa fa-tasks fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                    <div ><b>{{edp}}</b></div>
                </div>
            </div>
        </div>
        <a href="#">
            <div class="panel-footer">
                {% if  edp.recursos.count != 0 %}

                    <a href="{% url 'edp:responder_edp' edp.slug %}">
                        <div class="panel-footer">
                            <span class="pull-left">Responder EDA</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
               
                   {%endif%}
      
                <div class="clearfix"></div>
            </div>
        </a>
    </div>
</div>
{% endfor %}
</div>

{% endif %}

<div class="row">
        <div class="col-lg-12">
              
              <h3 class="page-header"> Todas as EDA disponiveis</h3>
        </div>
        <!-- /.col-lg-12 -->
      </div>
      
<table  class="table table-hover table-stripped table-responsive-sm table-sm">
    <thead>
      <tr>
        <th scope="col table-bordered">Título</th>
        <th scope="col">Habilidades</th>
        <th scope="col">Nível</th>
        <th scope="col">Data</th>
        <th scope="col">Professor(a)</th>
        <th scope="col"><abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr></th>
        <th scope="col"></th>

      </tr>
    </thead>
    {% for edp in edps%}
    <tbody>
      <tr>
        <th scope="row">


            <a  {% if edp.recursos and user.is_authenticated and user.eh_professor %} href="{{edp.get_absolute_url}}" {%endif%} >{{edp}}</a></th>
        <td>{% for h in edp.habilidades.all %}
            <ul class="list-group">
                <li class="ml-4">{{h}}</li>
            </ul>
            {%endfor%}</td>
        <td>{{edp.get_nivel_display}}</td>
        <td>{{edp.created_at |date:"d/m/Y"}}</td>
        <td>{{edp.usuario}}</td>
        <td>

            <small class="text-right" >
             {% if user.is_authenticated and user.eh_professor %}
                <a href="{% url 'edp:editar_edp' edp.slug %}" class="sm"><i class="fa fa-edit"></i></a>
                <a href="{% url 'edp:deletar_edp' edp.slug %}" class="sm"><i class="fa fa-trash"></i></a>


            </td>
            <td>
                {% if edp.recursos %}
                    <a href="{% url 'edp:editar_recursos' edp.slug %}" class="btn btn-sm btn-info "><i class="fa fa-edit"></i> Recursos</a>
                {% else %}
                    <a href="{% url 'edp:adicionar_recursos' edp.slug %}" class="btn btn-sm btn-warning "><i class="fa fa-plus"></i> Recursos</a>
                {% endif %}

                {% elif user.is_authenticated and user.eh_aluno %}



                {% if  edp.recursos.count != 0 %}
                <a href="{% url 'edp:responder_edp' edp.slug %}" class="btn btn-sm btn-info ">Responder <abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr></a>
               {%endif%}




                {% endif %}


            </small>

        </td>   {% empty%}
   <td>Nenhuma <abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr> disponível.</td>
      </tr>

    </tbody>

    {%endfor%}

  </table>


{% endblock %}

projeto/edp/templates/edp/listarEDArespondida.html
{% extends 'base.html' %} {% block title %} {{title}}{% endblock %} 
{%load widget_tweaks %}

                

{% block dashboard %}
{% if user.is_authenticated and user.eh_professor %}
<a href="{% url 'edp:nova_edp' %}" class="btn btn-success btn-lg ">Nova <abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr></a>
{% endif %}
<div style="padding: 10px;"></div>


<table class="table table-hover table-stripped table-responsive-sm table-sm">
    <thead>
      <tr>
        <th scope="col table-bordered">Título</th>
        <th scope="col">Habilidades</th>
        <th scope="col">Nível</th>
        <th scope="col">Data</th>
        <th scope="col">Professor(a)</th>
        <th scope="col"><abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr></th>
        <th scope="col"></th>
        
      </tr>
    </thead>
    {% for edp in edps%}
    <tbody>
      <tr>
        <th scope="row">
            
            
            <a  {% if edp.recursos %} href="{{edp.get_absolute_url}}" {%endif%} >{{edp}}</a></th>
        <td>{% for h in edp.habilidades.all %}
            <ul class="list-group">
                <li class="ml-4">{{h}}</li>
            </ul>
            {%endfor%}</td>
        <td>{{edp.get_nivel_display}}</td>
        <td>{{edp.created_at |date:"SHORT_DATE_FORMAT"}}</td>
        <td>{{edp.usuario}}</td>
        <td> 

            <small class="text-right" >
             {% if user.is_authenticated and user.eh_professor %}
                <a href="{% url 'edp:editar_edp' edp.slug %}" class="sm"><i class="fa fa-edit"></i> </a>
                <a href="{% url 'edp:deletar_edp' edp.slug %}" class="sm"><i class="fa fa-trash-alt "></i> </a>


            </td>
            <td>
                {% if edp.recursos %}
                    <a href="#" class="btn btn-sm btn-info "><i class="fa fa-edit"></i> Recursos</a>   
                {% else %}
                    <a href="{% url 'edp:adicionar_recursos' edp.slug %}" class="btn btn-sm btn-warning "><i class="fa fa-plus"></i> Recursos</a> 
                {% endif %}
    
                {% elif user.is_authenticated and user.eh_aluno %}

                
                
                {% if  edp.recursos %}
                <a href="{% url 'edp:responder_edp' edp.slug %}" class="btn btn-sm btn-info ">Responder <abbr title="Estrutura Digital de Aprendizagem" class="initialism">EDA</abbr></a>
               {%endif%}

                
               
                
                {% endif %}
                
    
            </small>
            
        </td>
      </tr>

    </tbody>
    {%endfor%}
  </table>


{% endblock %}